/**
 * Backend Template Injection — "One-Click Backend Setup"
 *
 * When the user selects "Add Firebase" or "Add Supabase":
 *   1. Creates the initialization file (firebase.js / supabaseClient.js)
 *   2. Populates it with standard init code using the user's secrets
 *   3. Automatically adds the SDK dependency to package.json
 */

import type { SecretEntry } from "./secrets-manager";

// ─── Types ───────────────────────────────────────────────────────────────────

export interface BackendInjectionResult {
  /** Files created / modified (path → content) */
  files: Record<string, string>;
  /** New dependencies added to package.json */
  addedDependencies: Record<string, string>;
  /** Human-readable summary */
  summary: string;
}

// ─── Firebase Template ───────────────────────────────────────────────────────

function buildFirebaseTemplate(secrets: SecretEntry[]): string {
  const getValue = (key: string) =>
    secrets.find((s) => s.key === key)?.value || `process.env.${key}`;

  return `// Firebase Configuration
// Auto-generated by Flare IDE — Cloud Integration Hub
// Docs: https://firebase.google.com/docs/web/setup

import { initializeApp } from "firebase/app";
import { getAuth } from "firebase/auth";
import { getFirestore } from "firebase/firestore";
import { getStorage } from "firebase/storage";

const firebaseConfig = {
  apiKey: "${getValue("NEXT_PUBLIC_FIREBASE_API_KEY")}",
  authDomain: "${getValue("NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN")}",
  projectId: "${getValue("NEXT_PUBLIC_FIREBASE_PROJECT_ID")}",
  storageBucket: "${getValue("NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET")}",
  messagingSenderId: "${getValue("NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID")}",
  appId: "${getValue("NEXT_PUBLIC_FIREBASE_APP_ID")}",
};

// Initialize Firebase
const app = initializeApp(firebaseConfig);

// Initialize Firebase services
export const auth = getAuth(app);
export const db = getFirestore(app);
export const storage = getStorage(app);

export default app;
`;
}

// ─── Supabase Template ───────────────────────────────────────────────────────

function buildSupabaseTemplate(secrets: SecretEntry[]): string {
  const supabaseUrl =
    secrets.find((s) => s.key === "NEXT_PUBLIC_SUPABASE_URL")?.value ||
    "process.env.NEXT_PUBLIC_SUPABASE_URL";
  const supabaseKey =
    secrets.find((s) => s.key === "NEXT_PUBLIC_SUPABASE_ANON_KEY")?.value ||
    "process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY";

  return `// Supabase Client Configuration
// Auto-generated by Flare IDE — Cloud Integration Hub
// Docs: https://supabase.com/docs/reference/javascript/initializing

import { createClient } from "@supabase/supabase-js";

const supabaseUrl = "${supabaseUrl}";
const supabaseKey = "${supabaseKey}";

export const supabase = createClient(supabaseUrl, supabaseKey);

export default supabase;
`;
}

// ─── Package.json Modifier ───────────────────────────────────────────────────

function addDependencyToPackageJson(
  existingPackageJson: string | undefined,
  dependencies: Record<string, string>,
): string {
  let pkg: any;

  try {
    pkg = existingPackageJson ? JSON.parse(existingPackageJson) : {};
  } catch {
    pkg = {};
  }

  if (!pkg.name) pkg.name = "flare-project";
  if (!pkg.version) pkg.version = "0.1.0";
  if (!pkg.private) pkg.private = true;
  if (!pkg.dependencies) pkg.dependencies = {};

  // Add dependencies (don't overwrite existing ones)
  for (const [name, version] of Object.entries(dependencies)) {
    if (!pkg.dependencies[name]) {
      pkg.dependencies[name] = version;
    }
  }

  return JSON.stringify(pkg, null, 2) + "\n";
}

// ─── Main Injection Functions ────────────────────────────────────────────────

/**
 * Inject Firebase backend files into the project.
 */
export function injectFirebaseBackend(
  existingFiles: Record<string, string>,
  secrets: SecretEntry[],
): BackendInjectionResult {
  const firebaseCode = buildFirebaseTemplate(secrets);
  const addedDeps: Record<string, string> = {
    firebase: "^10.12.0",
  };

  // Determine file path based on project structure
  const hasLib = Object.keys(existingFiles).some(
    (f) => f.includes("/lib/") || f.includes("/src/lib/"),
  );
  const hasSrc = Object.keys(existingFiles).some((f) => f.startsWith("/src/"));

  let filePath: string;
  if (hasLib) {
    filePath = hasSrc ? "/src/lib/firebase.js" : "/lib/firebase.js";
  } else if (hasSrc) {
    filePath = "/src/firebase.js";
  } else {
    filePath = "/firebase.js";
  }

  // Update package.json
  const existingPkg =
    existingFiles["/package.json"] || existingFiles["package.json"];
  const updatedPkg = addDependencyToPackageJson(existingPkg, addedDeps);

  const files: Record<string, string> = {
    [filePath]: firebaseCode,
    "/package.json": updatedPkg,
  };

  return {
    files,
    addedDependencies: addedDeps,
    summary: `✅ Firebase initialized!\n• Created ${filePath}\n• Added firebase SDK to package.json\n• Run \`npm install\` to install dependencies`,
  };
}

/**
 * Inject Supabase backend files into the project.
 */
export function injectSupabaseBackend(
  existingFiles: Record<string, string>,
  secrets: SecretEntry[],
): BackendInjectionResult {
  const supabaseCode = buildSupabaseTemplate(secrets);
  const addedDeps: Record<string, string> = {
    "@supabase/supabase-js": "^2.43.0",
  };

  // Determine file path based on project structure
  const hasLib = Object.keys(existingFiles).some(
    (f) => f.includes("/lib/") || f.includes("/src/lib/"),
  );
  const hasSrc = Object.keys(existingFiles).some((f) => f.startsWith("/src/"));

  let filePath: string;
  if (hasLib) {
    filePath = hasSrc ? "/src/lib/supabaseClient.js" : "/lib/supabaseClient.js";
  } else if (hasSrc) {
    filePath = "/src/supabaseClient.js";
  } else {
    filePath = "/supabaseClient.js";
  }

  // Update package.json
  const existingPkg =
    existingFiles["/package.json"] || existingFiles["package.json"];
  const updatedPkg = addDependencyToPackageJson(existingPkg, addedDeps);

  const files: Record<string, string> = {
    [filePath]: supabaseCode,
    "/package.json": updatedPkg,
  };

  return {
    files,
    addedDependencies: addedDeps,
    summary: `✅ Supabase initialized!\n• Created ${filePath}\n• Added @supabase/supabase-js to package.json\n• Run \`npm install\` to install dependencies`,
  };
}

/**
 * Helper: inject backend for any supported provider.
 */
export function injectBackend(
  provider: "firebase" | "supabase",
  existingFiles: Record<string, string>,
  secrets: SecretEntry[],
): BackendInjectionResult {
  switch (provider) {
    case "firebase":
      return injectFirebaseBackend(existingFiles, secrets);
    case "supabase":
      return injectSupabaseBackend(existingFiles, secrets);
    default:
      throw new Error(`Unsupported backend provider: ${provider}`);
  }
}
